// Generated by sensor-node/compile.mjs from src/esp8266-sensor-node.pas.
#pragma once
#include <Arduino.h>
#include "pmachine.h"

namespace sensor_program {
struct Instruction { uint8_t opcode; int number, count; const char* text; };
static const char text0[] PROGMEM = "raw";
static const char text1[] PROGMEM = "stable";
static const char text2[] PROGMEM = "previous";
static const char text3[] PROGMEM = "stamp";
static const char text4[] PROGMEM = "device.gpio_read";
static const char text5[] PROGMEM = "initialized";
static const char text6[] PROGMEM = "device.state_get";
static const char text7[] PROGMEM = "device.state_set";
static const char text8[] PROGMEM = "__discard";
static const char text9[] PROGMEM = "changed";
static const char text10[] PROGMEM = "device.clock";
static const char text11[] PROGMEM = "sampled";
static const char text12[] PROGMEM = "DHT11 sensor node ready";
static const char text13[] PROGMEM = "device.elapsed";
static const char text14[] PROGMEM = "Button pressed";
static const char text15[] PROGMEM = "device.dht_read";
static const char text16[] PROGMEM = "DHT11 temperature=";
static const char text17[] PROGMEM = "device.dht_temperature";
static const char text18[] PROGMEM = " C humidity=";
static const char text19[] PROGMEM = "device.dht_humidity";
static const char text20[] PROGMEM = " %";
static const char text21[] PROGMEM = "DHT11 read failed";
static const Instruction image[] PROGMEM = {
    {pmachine::OP_JMP, 1, 0, nullptr},
    {pmachine::OP_PUSH_INT, 0, 0, nullptr},
    {pmachine::OP_STORE_NAME, 0, 0, text0},
    {pmachine::OP_PUSH_INT, 0, 0, nullptr},
    {pmachine::OP_STORE_NAME, 0, 0, text1},
    {pmachine::OP_PUSH_INT, 0, 0, nullptr},
    {pmachine::OP_STORE_NAME, 0, 0, text2},
    {pmachine::OP_PUSH_INT, 0, 0, nullptr},
    {pmachine::OP_STORE_NAME, 0, 0, text3},
    {pmachine::OP_PUSH_INT, 14, 0, nullptr},
    {pmachine::OP_CALL_EXT, 0, 1, text4},
    {pmachine::OP_STORE_NAME, 0, 0, text0},
    {pmachine::OP_PUSH_STR, 0, 0, text5},
    {pmachine::OP_CALL_EXT, 0, 1, text6},
    {pmachine::OP_PUSH_INT, 0, 0, nullptr},
    {pmachine::OP_EQ, 0, 0, nullptr},
    {pmachine::OP_JZ, 41, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text5},
    {pmachine::OP_PUSH_INT, 1, 0, nullptr},
    {pmachine::OP_CALL_EXT, 0, 2, text7},
    {pmachine::OP_STORE_NAME, 0, 0, text8},
    {pmachine::OP_PUSH_STR, 0, 0, text0},
    {pmachine::OP_LOAD_NAME, 0, 0, text0},
    {pmachine::OP_CALL_EXT, 0, 2, text7},
    {pmachine::OP_STORE_NAME, 0, 0, text8},
    {pmachine::OP_PUSH_STR, 0, 0, text1},
    {pmachine::OP_LOAD_NAME, 0, 0, text0},
    {pmachine::OP_CALL_EXT, 0, 2, text7},
    {pmachine::OP_STORE_NAME, 0, 0, text8},
    {pmachine::OP_PUSH_STR, 0, 0, text9},
    {pmachine::OP_CALL_EXT, 0, 0, text10},
    {pmachine::OP_CALL_EXT, 0, 2, text7},
    {pmachine::OP_STORE_NAME, 0, 0, text8},
    {pmachine::OP_PUSH_STR, 0, 0, text11},
    {pmachine::OP_CALL_EXT, 0, 0, text10},
    {pmachine::OP_CALL_EXT, 0, 2, text7},
    {pmachine::OP_STORE_NAME, 0, 0, text8},
    {pmachine::OP_PUSH_STR, 0, 0, text12},
    {pmachine::OP_PRINT, 0, 0, nullptr},
    {pmachine::OP_PRINT_NL, 0, 0, nullptr},
    {pmachine::OP_JMP, 41, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text0},
    {pmachine::OP_CALL_EXT, 0, 1, text6},
    {pmachine::OP_STORE_NAME, 0, 0, text2},
    {pmachine::OP_LOAD_NAME, 0, 0, text0},
    {pmachine::OP_LOAD_NAME, 0, 0, text2},
    {pmachine::OP_NEQ, 0, 0, nullptr},
    {pmachine::OP_JZ, 57, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text0},
    {pmachine::OP_LOAD_NAME, 0, 0, text0},
    {pmachine::OP_CALL_EXT, 0, 2, text7},
    {pmachine::OP_STORE_NAME, 0, 0, text8},
    {pmachine::OP_PUSH_STR, 0, 0, text9},
    {pmachine::OP_CALL_EXT, 0, 0, text10},
    {pmachine::OP_CALL_EXT, 0, 2, text7},
    {pmachine::OP_STORE_NAME, 0, 0, text8},
    {pmachine::OP_JMP, 57, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text9},
    {pmachine::OP_CALL_EXT, 0, 1, text6},
    {pmachine::OP_STORE_NAME, 0, 0, text3},
    {pmachine::OP_PUSH_STR, 0, 0, text1},
    {pmachine::OP_CALL_EXT, 0, 1, text6},
    {pmachine::OP_STORE_NAME, 0, 0, text1},
    {pmachine::OP_LOAD_NAME, 0, 0, text3},
    {pmachine::OP_CALL_EXT, 0, 1, text13},
    {pmachine::OP_PUSH_INT, 50, 0, nullptr},
    {pmachine::OP_GE, 0, 0, nullptr},
    {pmachine::OP_LOAD_NAME, 0, 0, text0},
    {pmachine::OP_LOAD_NAME, 0, 0, text1},
    {pmachine::OP_NEQ, 0, 0, nullptr},
    {pmachine::OP_AND, 0, 0, nullptr},
    {pmachine::OP_JZ, 85, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text1},
    {pmachine::OP_LOAD_NAME, 0, 0, text0},
    {pmachine::OP_CALL_EXT, 0, 2, text7},
    {pmachine::OP_STORE_NAME, 0, 0, text8},
    {pmachine::OP_LOAD_NAME, 0, 0, text0},
    {pmachine::OP_PUSH_INT, 0, 0, nullptr},
    {pmachine::OP_EQ, 0, 0, nullptr},
    {pmachine::OP_JZ, 84, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text14},
    {pmachine::OP_PRINT, 0, 0, nullptr},
    {pmachine::OP_PRINT_NL, 0, 0, nullptr},
    {pmachine::OP_JMP, 84, 0, nullptr},
    {pmachine::OP_JMP, 85, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text11},
    {pmachine::OP_CALL_EXT, 0, 1, text6},
    {pmachine::OP_STORE_NAME, 0, 0, text3},
    {pmachine::OP_LOAD_NAME, 0, 0, text3},
    {pmachine::OP_CALL_EXT, 0, 1, text13},
    {pmachine::OP_PUSH_INT, 5000, 0, nullptr},
    {pmachine::OP_GE, 0, 0, nullptr},
    {pmachine::OP_JZ, 116, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text11},
    {pmachine::OP_CALL_EXT, 0, 0, text10},
    {pmachine::OP_CALL_EXT, 0, 2, text7},
    {pmachine::OP_STORE_NAME, 0, 0, text8},
    {pmachine::OP_PUSH_INT, 4, 0, nullptr},
    {pmachine::OP_CALL_EXT, 0, 1, text15},
    {pmachine::OP_JZ, 112, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text16},
    {pmachine::OP_PRINT, 0, 0, nullptr},
    {pmachine::OP_CALL_EXT, 0, 0, text17},
    {pmachine::OP_PRINT, 0, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text18},
    {pmachine::OP_PRINT, 0, 0, nullptr},
    {pmachine::OP_CALL_EXT, 0, 0, text19},
    {pmachine::OP_PRINT, 0, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text20},
    {pmachine::OP_PRINT, 0, 0, nullptr},
    {pmachine::OP_PRINT_NL, 0, 0, nullptr},
    {pmachine::OP_JMP, 115, 0, nullptr},
    {pmachine::OP_PUSH_STR, 0, 0, text21},
    {pmachine::OP_PRINT, 0, 0, nullptr},
    {pmachine::OP_PRINT_NL, 0, 0, nullptr},
    {pmachine::OP_JMP, 116, 0, nullptr},
    {pmachine::OP_HALT, 0, 0, nullptr}
};
constexpr size_t count = sizeof(image) / sizeof(image[0]);
inline pmachine::PInstruction at(size_t index) {
    Instruction stored;
    memcpy_P(&stored, &image[index], sizeof(stored));
    pmachine::PInstruction result;
    result.opcode = stored.opcode;
    result.intOperand = stored.number;
    result.address = stored.number;
    result.value = stored.count;
    if (stored.text) {
        result.strOperand = String(FPSTR(stored.text)).c_str();
        result.type = pmachine::OperandType::STRING;
    } else if (stored.opcode == pmachine::OP_PUSH_INT) result.type = pmachine::OperandType::INT;
    return result;
}
}
