import fs from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { compilePascalishProgramWithAntlr } from '../aggregator/scripts/compile-pascalish-program-antlr-to-pcode.mjs';
import { parsePcode } from '../pmachines/javascript/src/runtime.mjs';

const sourceUrl = new URL('../src/esp8266-sensor-node.pas', import.meta.url);
export const imageUrl = new URL('../src/sensor_node/program.h', import.meta.url);

export async function compileSensorNode() {
  const source = await fs.readFile(sourceUrl, 'utf8');
  return compilePascalishProgramWithAntlr(source, { fileName: fileURLToPath(sourceUrl), deviceBindings: true });
}

export function generateImage(compiled) {
  const instructions = parsePcode(compiled.pcodeText);
  const strings = new Map();
  const stringId = value => {
    if (!strings.has(value)) strings.set(value, strings.size);
    return `text${strings.get(value)}`;
  };
  const plain = new Set(['HALT', 'PRINT', 'PRINT_NL', 'PRINT_INT', 'EQ', 'NEQ', 'LT', 'LE', 'GT', 'GE', 'AND', 'OR', 'NOT', 'ADD', 'SUB', 'MUL', 'DIV']);
  const rows = instructions.map(instruction => {
    const op = instruction.mnemonic;
    let number = 0, count = 0, text = 'nullptr';
    if (op === 'PUSH_INT') number = instruction.operand;
    else if (['PUSH_STR', 'LOAD', 'STORE'].includes(op)) text = stringId(instruction.operand);
    else if (['JMP', 'JZ'].includes(op)) {
      number = instruction.targetIndex;
      if (!Number.isInteger(number) || number < 0) throw new Error(`Unresolved sensor jump: ${instruction.operand}`);
    } else if (op === 'CALL_EXT') {
      text = stringId(instruction.operand.label);
      count = instruction.operand.argc;
    } else if (!plain.has(op)) throw new Error(`Unsupported flash image instruction: ${op}`);
    if (!Number.isSafeInteger(number) || number < -2147483648 || number > 2147483647
      || !Number.isSafeInteger(count) || count < 0 || count > 8) throw new Error(`Invalid sensor instruction: ${op}`);
    const symbol = op === 'LOAD' || op === 'STORE' ? `${op}_NAME` : op;
    return `    {pmachine::OP_${symbol}, ${number}, ${count}, ${text}}`;
  });
  return `// Generated by sensor-node/compile.mjs from src/esp8266-sensor-node.pas.
#pragma once
#include <Arduino.h>
#include "pmachine.h"

namespace sensor_program {
struct Instruction { uint8_t opcode; int number, count; const char* text; };
${[...strings].map(([value, id]) => `static const char text${id}[] PROGMEM = ${JSON.stringify(value)};`).join('\n')}
static const Instruction image[] PROGMEM = {
${rows.join(',\n')}
};
constexpr size_t count = sizeof(image) / sizeof(image[0]);
inline pmachine::PInstruction at(size_t index) {
    Instruction stored;
    memcpy_P(&stored, &image[index], sizeof(stored));
    pmachine::PInstruction result;
    result.opcode = stored.opcode;
    result.intOperand = stored.number;
    result.address = stored.number;
    result.value = stored.count;
    if (stored.text) {
        result.strOperand = String(FPSTR(stored.text)).c_str();
        result.type = pmachine::OperandType::STRING;
    } else if (stored.opcode == pmachine::OP_PUSH_INT) result.type = pmachine::OperandType::INT;
    return result;
}
}
`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const image = generateImage(await compileSensorNode());
  if (process.argv.includes('--check')) {
    if (await fs.readFile(imageUrl, 'utf8') !== image) throw new Error('Sensor image is stale; run node sensor-node\\compile.mjs');
    console.log('Sensor Pascalish flash image is current');
  } else {
    await fs.writeFile(imageUrl, image);
    console.log(`Generated ${fileURLToPath(imageUrl)}`);
  }
}
