[platformio]
src_dir = ..

[env:esp8266_sensor]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    bblanchon/ArduinoJson
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
build_unflags = -std=gnu++11 -fno-exceptions
build_flags =
    -std=gnu++17
    -fexceptions
    -DPULSE_ESP8266_SENSOR
    -I../src
    -I../pmachines/arduino/src
build_src_filter =
    -<*>
    +<src/sensor_node/main.cpp>
    +<src/GpioPinSemaphore.cpp>
    +<src/StringPool.cpp>
    +<src/ffs/FederatedFileSystem.cpp>
    +<pmachines/arduino/src/pmachine.cpp>
