#!/usr/bin/env bash
# Installs PULSE systemd unit files generated by generate-systemd-units.mjs
# into /etc/systemd/system, then enables (does not start) them.
#
# Usage: sudo ./install-services.sh [--start]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
UNITS_DIR="$REPO_ROOT/deploy/systemd"
START_NOW=0

for arg in "$@"; do
  if [ "$arg" = "--start" ]; then START_NOW=1; fi
done

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root (sudo) — systemd unit installation requires it." >&2
  exit 1
fi

if [ ! -d "$UNITS_DIR" ] || [ -z "$(ls -A "$UNITS_DIR"/*.service 2>/dev/null)" ]; then
  echo "No unit files found in $UNITS_DIR — run 'node aggregator/scripts/linux/generate-systemd-units.mjs' first." >&2
  exit 1
fi

for unit_path in "$UNITS_DIR"/*.service; do
  unit_name="$(basename "$unit_path")"
  echo "Installing $unit_name..."
  cp "$unit_path" "/etc/systemd/system/$unit_name"
done

systemctl daemon-reload

for unit_path in "$UNITS_DIR"/*.service; do
  unit_name="$(basename "$unit_path")"
  systemctl enable "$unit_name"
  if [ "$START_NOW" -eq 1 ]; then
    systemctl restart "$unit_name"
    systemctl --no-pager status "$unit_name" || true
  fi
done

echo "Done. Use 'systemctl status <unit>' or 'journalctl -u <unit> -f' to check on a service."
