import { createVisualObject } from './catalogModel'

export const SEEDED_CATALOG_OBJECTS = Object.freeze([
  createVisualObject({
    id: 'daemon.gateway.primary',
    name: 'Primary Gateway',
    kind: 'daemon',
    type: 'gateway',
    source: 'seeded',
    usageNotes: 'Use this as the default ingress endpoint for new flows. Reuse before creating additional gateways.',
    status: 'planned',
    location: 'platform/edge',
    tags: ['permanent', 'ingress', 'edge'],
    capabilities: ['route messages', 'terminate http', 'bridge device traffic'],
    properties: [
      { id: 'protocols', label: 'Protocols', valueType: 'collection', value: 'HTTP, MQTT, Queue ingress', readOnly: true },
      { id: 'highAvailabilityMode', label: 'HA Mode', valueType: 'enum', value: 'active-passive', readOnly: true },
    ],
    relationships: [
      { type: 'depends-on', targetId: 'daemon.message-broker.primary', label: 'depends on broker' },
    ],
  }),
  createVisualObject({
    id: 'daemon.message-broker.primary',
    name: 'Primary Message Broker',
    kind: 'daemon',
    type: 'message-broker',
    source: 'seeded',
    usageNotes: 'Prefer this broker for all internal flow hops unless isolation requirements demand a dedicated broker.',
    status: 'active',
    location: 'platform/messaging',
    tags: ['permanent', 'broker'],
    capabilities: ['broker transport', 'federation', 'queue bindings'],
    properties: [
      { id: 'brokerEngine', label: 'Broker Engine', valueType: 'enum', value: 'pulse-broker', readOnly: true },
      { id: 'federationMode', label: 'Federation', valueType: 'enum', value: 'clustered', readOnly: true },
    ],
  }),
  createVisualObject({
    id: 'daemon.queue-manager.primary',
    name: 'Primary Queue Manager',
    kind: 'daemon',
    type: 'queue-manager',
    source: 'seeded',
    usageNotes: 'Attach new queues to this manager first to keep operations centralized.',
    status: 'active',
    location: 'platform/messaging',
    tags: ['permanent', 'queues'],
    properties: [
      { id: 'managerId', label: 'Manager Id', valueType: 'string', value: 'primary-qm', readOnly: true },
      { id: 'queueCount', label: 'Queue Count', valueType: 'integer', value: 2, readOnly: true },
    ],
    relationships: [
      { type: 'managed-by', targetId: 'daemon.message-broker.primary', label: 'managed by broker' },
    ],
  }),
  createVisualObject({
    id: 'daemon.data-librarian.primary',
    name: 'Data Librarian',
    kind: 'daemon',
    type: 'data-librarian',
    source: 'seeded',
    usageNotes: 'Use this as the catalog authority when introducing new reusable objects, maps, and contracts.',
    status: 'active',
    location: 'platform/catalog',
    tags: ['permanent', 'catalog', 'authority'],
    capabilities: ['seed initial catalog', 'curate permanent object types', 'govern reusable artifacts'],
    properties: [
      { id: 'catalogDomains', label: 'Catalog Domains', valueType: 'collection', value: 'daemons, services, devices, maps, queues', readOnly: true },
      { id: 'authorityLevel', label: 'Authority', valueType: 'enum', value: 'authoritative-seed', readOnly: true },
    ],
    relationships: [
      { type: 'depends-on', targetId: 'daemon.gateway.primary', label: 'publishes through gateway' },
    ],
  }),
  createVisualObject({
    id: 'service.router.primary',
    name: 'Router Engine',
    kind: 'service',
    type: 'router-service',
    source: 'seeded',
    usageNotes: 'Start new routing workflows here before adding specialized routers.',
    status: 'active',
    location: 'platform/routing',
    capabilities: ['route MT103', 'route PACS', 'drive edge ingress'],
    properties: [
      { id: 'inputTypes', label: 'Input Types', valueType: 'collection', value: 'swift.mt103, iso20022.pacs008', readOnly: true },
      { id: 'outputQueues', label: 'Output Queues', valueType: 'collection', value: 'swift.mt103.normalized, iso20022.dispatch', readOnly: true },
    ],
    relationships: [
      { type: 'publishes-to', targetId: 'queue.swift.mt103.inbound', label: 'publishes to inbound queue' },
    ],
  }),
  createVisualObject({
    id: 'service.mapper.primary',
    name: 'Mapper Engine',
    kind: 'service',
    type: 'mapper-service',
    source: 'seeded',
    usageNotes: 'Reuse this mapper for MT103 to PACS.008 transformations when possible.',
    status: 'active',
    location: 'platform/mapping',
    capabilities: ['strongly typed transform', 'canonical mapping', 'queryable map execution'],
    properties: [
      { id: 'sourceType', label: 'Source Type', valueType: 'type-ref', value: 'swift.mt103', readOnly: true },
      { id: 'targetType', label: 'Target Type', valueType: 'type-ref', value: 'iso20022.pacs008', readOnly: true },
    ],
    relationships: [
      { type: 'maps-to', targetId: 'map.mt103-to-pacs008', label: 'executes map' },
    ],
  }),
  createVisualObject({
    id: 'map.mt103-to-pacs008',
    name: 'MT103 -> PACS.008',
    kind: 'map',
    type: 'message-map',
    source: 'seeded',
    usageNotes: 'Canonical transformation map. Reference this map from new payment flows.',
    status: 'defined',
    location: 'librarian/maps',
    tags: ['pascalish', 'typed'],
    properties: [
      { id: 'sourceType', label: 'Source Type', valueType: 'type-ref', value: 'swift.mt103', readOnly: true },
      { id: 'targetType', label: 'Target Type', valueType: 'type-ref', value: 'iso20022.pacs008', readOnly: true },
    ],
  }),
  createVisualObject({
    id: 'queue.swift.mt103.inbound',
    name: 'swift.mt103.inbound',
    kind: 'queue',
    type: 'durable-queue',
    source: 'seeded',
    usageNotes: 'Use for inbound MT103 ingestion. Avoid creating parallel inbound queues unless necessary.',
    status: 'active',
    location: 'primary-qm',
    properties: [
      { id: 'messageType', label: 'Message Type', valueType: 'type-ref', value: 'swift.mt103', readOnly: true },
      { id: 'retentionPolicy', label: 'Retention', valueType: 'enum', value: 'durable', readOnly: true },
    ],
  }),
  createVisualObject({
    id: 'queue.iso20022.dispatch',
    name: 'iso20022.dispatch',
    kind: 'queue',
    type: 'durable-queue',
    source: 'seeded',
    usageNotes: 'Standard dispatch queue for PACS outputs. Reuse for downstream ISO handling.',
    status: 'defined',
    location: 'primary-qm',
    properties: [
      { id: 'messageType', label: 'Message Type', valueType: 'type-ref', value: 'iso20022.pacs008', readOnly: true },
      { id: 'retentionPolicy', label: 'Retention', valueType: 'enum', value: 'durable', readOnly: true },
    ],
  }),
])