#pragma once

#ifndef DEVICE_ROLE
#define DEVICE_ROLE "generalist"
#endif

#ifndef PROFILE_MAX_MESSAGE_BYTES
#define PROFILE_MAX_MESSAGE_BYTES 16384
#endif

#ifndef PROFILE_MAX_CONCURRENT_TASKS
#define PROFILE_MAX_CONCURRENT_TASKS 2
#endif

#ifndef PROFILE_PREFERRED_TASK_TYPE
#define PROFILE_PREFERRED_TASK_TYPE "balanced"
#endif

#ifndef FIRMWARE_TRACK
#define FIRMWARE_TRACK "stable"
#endif

#ifndef SUPERVISOR_DEFAULT_ENABLED
#define SUPERVISOR_DEFAULT_ENABLED 0
#endif

#ifndef SUPERVISOR_REQUIRE_FRONTEND
#define SUPERVISOR_REQUIRE_FRONTEND 1
#endif

#ifndef SUPERVISOR_CHECK_INTERVAL_MS
#define SUPERVISOR_CHECK_INTERVAL_MS 5000
#endif

#ifndef SUPERVISOR_BACKEND_URL
#define SUPERVISOR_BACKEND_URL ""
#endif

#ifndef SUPERVISOR_FRONTEND_URL
#define SUPERVISOR_FRONTEND_URL ""
#endif

#ifndef SUPERVISOR_HEARTBEAT_URL
#define SUPERVISOR_HEARTBEAT_URL ""
#endif

#ifndef PROFILE_PCODE_SIGNING_KEY
#define PROFILE_PCODE_SIGNING_KEY "dev-insecure-key-change-me"
#endif

#ifndef PROFILE_PCODE_SIGNING_KEY_ID
#define PROFILE_PCODE_SIGNING_KEY_ID "profile-default"
#endif
